name: Main

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: 'actions/checkout@v4'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install the Node.js dependencies
        run: bun install

      - name: Build all
        run: bun run build

      - name: Test all
        run: bun run test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Check out the repo
        uses: 'actions/checkout@v4'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          commit: 'chore: release'
          title: 'Release'
          publish: bun run changeset:release
          version: bun run changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
